seed: 42

data:
  name: simple
  root: ./data/pcontext_like
  img_size: 512
  num_seen: 49

model:
  name: student
  backbone: tf_efficientnetv2_s_in21k
  feat_dim: 256
  clip_dim: 512

clip:
  backbone: ViT-B-16
  pretrained: openai
  bank_size: 24

loss:
  temperature: 0.07
  w_global: 1.0
  w_local: 1.0
  w_ce: 1.0

train:
  batch_size: 8
  val_batch_size: 8
  lr: 3.0e-4
  weight_decay: 0.01
  max_iters: 40000
  grad_clip: 1.0
  eval_every: 1
  print_freq: 50